basePath: /
definitions:
  request.Task:
    properties:
      state:
        type: integer
    type: object
  work_flow.GzlAppUser:
    properties:
      appId:
        type: integer
      userId:
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample Server pets
  title: Work Flow API
  version: 0.0.1
paths:
  /base/captcha:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"验证码获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 生成验证码
      tags:
      - Base
  /form/formdata:
    get:
      parameters:
      - description: string
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/work_flow.GzlAppUser'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"null"}'
          schema:
            type: string
      summary: 返回之前填写过的表单数据
      tags:
      - form
  /form/formempty:
    get:
      parameters:
      - description: string
        in: body
        name: data
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"null"}'
          schema:
            type: string
      summary: 需要用户填写的空表单
      tags:
      - form
  /form/formsave:
    post:
      parameters:
      - description: string
        in: body
        name: data
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"null"}'
          schema:
            type: string
      summary: 保存用户填写的表单
      tags:
      - form
  /jwt/jsonInBlacklist:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"拉黑成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: jwt加入黑名单
      tags:
      - Jwt
  /task/dynamic:
    get:
      parameters:
      - description: string
        in: body
        name: data
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 流程动态信息
      tags:
      - Task
  /task/inspect:
    post:
      parameters:
      - description: 通过||拒绝
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Task'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"已审核"}'
          schema:
            type: string
      summary: 审批（通过||拒绝）
      tags:
      - Task
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
